### ISSUE TITLE
Date in plugin.info.txt

### ISSUE THREAD

**Issue by khaledblah** [rabidaudio/dokuwiki-plugin-autostartpage#1]
Hi,

thanks for your work on this plugin!

I believe the date in plugin.info.txt needs to be fixed, its value should be: 2013-07-19
Currently the value is "2013-07-12" and thus the extension manager claims there is an update for this plugin when there isn't one.

**Comment by rabidaudio** [comment]
Thanks. I finally got around to reinstalling dokuwiki so i fixed this (763d1f9) and a few other things. There really is an update now, but it shouldn't be a problem after that.

Cheers

Charles
